# Generated by Django 5.2.7 on 2025-10-23 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Aseguradadora',
                'verbose_name_plural': 'Aseguradados',
                'db_table': 'aseguradadora',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('identificacion', models.CharField(max_length=50, unique=True, verbose_name='Identificacion')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electronico')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='Imagen')),
                ('cv', models.FileField(blank=True, null=True, upload_to='vitae', verbose_name='Curriculum Vitae')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Granda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Apellidos',
                'verbose_name_plural': 'Apellidos',
                'db_table': 'apellido',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de empleado')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipo',
            },
        ),
        migrations.CreateModel(
            name='TypeSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Seguro',
                'verbose_name_plural': 'Seguros',
                'db_table': 'seguro',
            },
        ),
        migrations.CreateModel(
            name='Kliuwher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electronico')),
                ('Direcion', models.CharField(max_length=40, verbose_name='Direcion')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('id_pais', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manejo_seguros.granda')),
            ],
            options={
                'verbose_name': 'Nombre',
                'verbose_name_plural': 'Nombres',
                'db_table': 'nombre',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electronico')),
                ('address', models.TextField(max_length=300, verbose_name='Dirección')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Salario')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='Imagen')),
                ('cv', models.ImageField(blank=True, null=True, upload_to='vitae', verbose_name='Curriculum Vitae')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('category', models.ManyToManyField(to='manejo_seguros.category')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manejo_seguros.type')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPoliza', models.CharField(max_length=50, unique=True, verbose_name='Poliza')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor del seguro')),
                ('valor_prima', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor Prima')),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor Adicional')),
                ('Aseguradora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manejo_seguros.aseguradadora')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manejo_seguros.cliente')),
                ('type_Seguro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manejo_seguros.typeseguro')),
            ],
            options={
                'verbose_name': 'Poliza',
                'verbose_name_plural': 'Polizas',
                'db_table': 'poliza',
            },
        ),
    ]
